export const AUTH_STATUS = 'AUTH_STATUS';
export const FETCH_STREAMS = 'FETCH_STREAMS';
export const FETCH_STREAM = 'FETCH_STREAM';
export const CREATE_STREAM = 'CREATE_STREAM';
export const EDIT_STREAM = 'EDIT_STREAM';
export const DELECT_STREAM = 'DELECT_STREAM';

